/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* AGREEMENT APP*/
export const AGREEMENT_UNAUTHORIZED = "AGREEMENT_UNAUTHORIZED";
export const AGREEMENT_GET_LIST = "AGREEMENT_GET_LIST";
export const AGREEMENT_GET_LIST_SUCCESS = "AGREEMENT_GET_LIST_SUCCESS";
export const AGREEMENT_GET_LIST_ERROR = "AGREEMENT_GET_LIST_ERROR";
export const AGREEMENT_GET_LIST_WITH_FILTER = "AGREEMENT_GET_LIST_WITH_FILTER";
export const AGREEMENT_GET_LIST_WITH_ORDER = "AGREEMENT_GET_LIST_WITH_ORDER";
export const AGREEMENT_GET_LIST_SEARCH = "AGREEMENT_GET_LIST_SEARCH";
export const AGREEMENT_ADD_ITEM = "AGREEMENT_ADD_ITEM";
export const AGREEMENT_ADD_ITEM_SUCCESS = "AGREEMENT_ADD_ITEM_SUCCESS";
export const AGREEMENT_ADD_ITEM_ERROR = "AGREEMENT_ADD_ITEM_ERROR";
export const AGREEMENT_DELETE_ITEM = "AGREEMENT_DELETE_ITEM";
export const AGREEMENT_DELETE_ITEM_SUCCESS = "AGREEMENT_DELETE_ITEM_SUCCESS";
export const AGREEMENT_DELETE_ITEM_ERROR = "AGREEMENT_DELETE_ITEM_ERROR";
export const AGREEMENT_SEARCH = "AGREEMENT_SEARCH";
export const AGREEMENT_SEARCH_SUCCESS = "AGREEMENT_SEARCH_SUCCESS";
export const AGREEMENT_SEARCH_ERROR = "AGREEMENT_SEARCH_ERROR";
export const AGREEMENT_SELECTED_ITEMS_CHANGE = "AGREEMENT_SELECTED_ITEMS_CHANGE";

export * from "./menu/actions";
export * from "./settings/actions";
export * from "./auth/actions";
export * from "./agreements/actions";